[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Increase the function timeout for Next.js builds
  node_bundler = "esbuild"
  external_node_modules = ["@next/env"]

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "next" 